#!/bin/bash
echo -e "\033[0m"

echo -e "\033[1m[Programs]\033[0m";
echo -e "  Md+p:                   Lancer";
echo -e "  Md+b/f:          Browser/Files";
echo -e "  Md+Sh+Enter:          Terminal";
echo -e "  Md+Sh+a:             Volume up";
echo -e "  Md+Sh+z:           Volume down";
echo -e "\033[0m"

echo -e "\033[1m[Tiling]\033[0m";
echo -e "  Md+t:                  Classic";
echo -e "  Md+f:                 Floating";
echo -e "  Md+x/h:             Horizontal";
echo -e "  Md+m:               Fullscreen";
echo -e "  Md+Sh+space:        Make float";
echo -e "  Md+space:               Circle";
echo -e "  Md+h/l:                 Resize";
echo -e "  Md+j/k:                 Select";
echo -e "  Md+q:                     Kill";
echo -e "  Md+Sh+q:                  Quit";
echo -e "\033[0m"

echo -e "\033[1m[URxvt]\033[0m";
echo -e "  Alt+c:                    Copy";
echo -e "  Alt+V:                   Paste";
echo -e "\033[0m"

#Esc[0m 	Turn format off 
#Esc[1m 	Turn bold mode on 
#Esc[2m 	Turn low intensity mode on 
#Esc[4m 	Turn underline mode on 
#Esc[5m 	Turn blinking mode on 
#Esc[7m 	Turn reverse video on 
#Esc[8m 	Turn invisible text mode on 
